### ISSUE TITLE
UrlBlockList.cpp fails build on g++ version 4.9.4 and Travis CL

### ISSUE THREAD

**Issue by MikeLx** [privacore/open-source-search-engine#5]
UrlBlockList.cpp fails build. atomic_store not in std?  g++ version 4.9.4, Ubuntu Server 14.04.5. Possible quick fix/new feature: Add parm option to return to using GBmutex and/or not use URLBlocklist.

g++ -D_REENTRANT_ -I. -g -fno-stack-protector -DPTHREADS -std=c++11 -march=core-avx-i -msse4.2  -MMD -MP -Wall -Wformat-security -Wno-invalid-offsetof -Wno-unused-result -Wstrict-aliasing=0 -Wno-write-strings -Wno-maybe-uninitialized -Wno-unused-but-set-variable -Wno-unused-parameter  -O3 -c UrlBlockList.cpp
UrlBlockList.cpp: In member function ‘void UrlBlockList::swapUrlRegexList(regexlistconst_ptr_t)’:
UrlBlockList.cpp:100:49: error: no matching function for call to ‘atomic_store(regexlistconst_ptr_t*, regexlistconst_ptr_t&)’
  std::atomic_store(&m_urlRegexList, urlRegexList);
                                                 ^
UrlBlockList.cpp:100:49: note: candidates are:
In file included from UrlBlockList.cpp:7:0:
/usr/include/c++/4.9/atomic:896:5: note: template<class _ITp> void std::atomic_store(std::atomic<_ITp>*, _ITp)
     atomic_store(atomic<_ITp>* __a, _ITp __i) noexcept
     ^
/usr/include/c++/4.9/atomic:896:5: note:   template argument deduction/substitution failed:
UrlBlockList.cpp:100:49: note:   ‘regexlistconst_ptr_t {aka std::shared_ptr<const std::vector<std::pair<std::basic_string<char>, std::basic_regex<char> > > >}’ is not derived from ‘std::atomic<_ITp>’
  std::atomic_store(&m_urlRegexList, urlRegexList);
                                                 ^
In file included from UrlBlockList.cpp:7:0:
/usr/include/c++/4.9/atomic:901:5: note: template<class _ITp> void std::atomic_store(volatile std::atomic<_ITp>*, _ITp)
     atomic_store(volatile atomic<_ITp>* __a, _ITp __i) noexcept
     ^
/usr/include/c++/4.9/atomic:901:5: note:   template argument deduction/substitution failed:
UrlBlockList.cpp:100:49: note:   ‘regexlistconst_ptr_t {aka std::shared_ptr<const std::vector<std::pair<std::basic_string<char>, std::basic_regex<char> > > >}’ is not derived from ‘volatile std::atomic<_ITp>’
  std::atomic_store(&m_urlRegexList, urlRegexList);
                                                 ^
make: *** [UrlBlockList.o] Error 1

**Comment by MikeLx** [comment]
Appears to work fine with g++ 6.2

**Comment by br-privacore** [comment]
I have disabled the feature for now.

**Comment by MikeLx** [comment]
Thanks!

**Comment by br-privacore** [comment]
We are now requiring g++ 5.4 and Ubuntu 16.
